// flow-typed signature: 7cf8f9924128257a17a789aba039f735
// flow-typed version: <<STUB>>/detox_v^5.0.12/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'detox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'detox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'detox/lib/client/actions/actions' {
  declare module.exports: any;
}

declare module 'detox/lib/client/AsyncWebSocket' {
  declare module.exports: any;
}

declare module 'detox/lib/client/AsyncWebSocket.test' {
  declare module.exports: any;
}

declare module 'detox/lib/client/Client' {
  declare module.exports: any;
}

declare module 'detox/lib/client/Client.test' {
  declare module.exports: any;
}

declare module 'detox/lib/configuration' {
  declare module.exports: any;
}

declare module 'detox/lib/configuration.test' {
  declare module.exports: any;
}

declare module 'detox/lib/configurations.mock' {
  declare module.exports: any;
}

declare module 'detox/lib/Detox' {
  declare module.exports: any;
}

declare module 'detox/lib/Detox.test' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/Device' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/Device.test' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/Emulator' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/Fbsimctl' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/Fbsimctl.test' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/IosNoneDevice' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/Simulator' {
  declare module.exports: any;
}

declare module 'detox/lib/devices/Simulator.test' {
  declare module.exports: any;
}

declare module 'detox/lib/errors/CustomError' {
  declare module.exports: any;
}

declare module 'detox/lib/errors/CustomError.test' {
  declare module.exports: any;
}

declare module 'detox/lib/index' {
  declare module.exports: any;
}

declare module 'detox/lib/index.test' {
  declare module.exports: any;
}

declare module 'detox/lib/invoke' {
  declare module.exports: any;
}

declare module 'detox/lib/invoke.test' {
  declare module.exports: any;
}

declare module 'detox/lib/invoke/EarlGrey' {
  declare module.exports: any;
}

declare module 'detox/lib/invoke/Invoke' {
  declare module.exports: any;
}

declare module 'detox/lib/ios/expect' {
  declare module.exports: any;
}

declare module 'detox/lib/ios/expect.test' {
  declare module.exports: any;
}

declare module 'detox/lib/ios/matchers' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/argparse' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/argparse.test' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/exec' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/exec.test' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/retry' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/retry.test' {
  declare module.exports: any;
}

declare module 'detox/lib/utils/uuid' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-build' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-init' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-run-server' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox-test' {
  declare module.exports: any;
}

declare module 'detox/local-cli/detox' {
  declare module.exports: any;
}

declare module 'detox/local-cli/templates/mocha' {
  declare module.exports: any;
}

declare module 'detox/scripts/clean-build' {
  declare module.exports: any;
}

declare module 'detox/src/client/actions/actions' {
  declare module.exports: any;
}

declare module 'detox/src/client/AsyncWebSocket' {
  declare module.exports: any;
}

declare module 'detox/src/client/Client' {
  declare module.exports: any;
}

declare module 'detox/src/configuration' {
  declare module.exports: any;
}

declare module 'detox/src/configurations.mock' {
  declare module.exports: any;
}

declare module 'detox/src/Detox' {
  declare module.exports: any;
}

declare module 'detox/src/devices/Device' {
  declare module.exports: any;
}

declare module 'detox/src/devices/Emulator' {
  declare module.exports: any;
}

declare module 'detox/src/devices/Fbsimctl' {
  declare module.exports: any;
}

declare module 'detox/src/devices/IosNoneDevice' {
  declare module.exports: any;
}

declare module 'detox/src/devices/Simulator' {
  declare module.exports: any;
}

declare module 'detox/src/errors/CustomError' {
  declare module.exports: any;
}

declare module 'detox/src/index' {
  declare module.exports: any;
}

declare module 'detox/src/invoke' {
  declare module.exports: any;
}

declare module 'detox/src/invoke/EarlGrey' {
  declare module.exports: any;
}

declare module 'detox/src/invoke/Invoke' {
  declare module.exports: any;
}

declare module 'detox/src/ios/expect' {
  declare module.exports: any;
}

declare module 'detox/src/ios/matchers' {
  declare module.exports: any;
}

declare module 'detox/src/utils/argparse' {
  declare module.exports: any;
}

declare module 'detox/src/utils/exec' {
  declare module.exports: any;
}

declare module 'detox/src/utils/retry' {
  declare module.exports: any;
}

declare module 'detox/src/utils/uuid' {
  declare module.exports: any;
}

declare module 'detox/wallaby' {
  declare module.exports: any;
}

// Filename aliases
declare module 'detox/lib/client/actions/actions.js' {
  declare module.exports: $Exports<'detox/lib/client/actions/actions'>;
}
declare module 'detox/lib/client/AsyncWebSocket.js' {
  declare module.exports: $Exports<'detox/lib/client/AsyncWebSocket'>;
}
declare module 'detox/lib/client/AsyncWebSocket.test.js' {
  declare module.exports: $Exports<'detox/lib/client/AsyncWebSocket.test'>;
}
declare module 'detox/lib/client/Client.js' {
  declare module.exports: $Exports<'detox/lib/client/Client'>;
}
declare module 'detox/lib/client/Client.test.js' {
  declare module.exports: $Exports<'detox/lib/client/Client.test'>;
}
declare module 'detox/lib/configuration.js' {
  declare module.exports: $Exports<'detox/lib/configuration'>;
}
declare module 'detox/lib/configuration.test.js' {
  declare module.exports: $Exports<'detox/lib/configuration.test'>;
}
declare module 'detox/lib/configurations.mock.js' {
  declare module.exports: $Exports<'detox/lib/configurations.mock'>;
}
declare module 'detox/lib/Detox.js' {
  declare module.exports: $Exports<'detox/lib/Detox'>;
}
declare module 'detox/lib/Detox.test.js' {
  declare module.exports: $Exports<'detox/lib/Detox.test'>;
}
declare module 'detox/lib/devices/Device.js' {
  declare module.exports: $Exports<'detox/lib/devices/Device'>;
}
declare module 'detox/lib/devices/Device.test.js' {
  declare module.exports: $Exports<'detox/lib/devices/Device.test'>;
}
declare module 'detox/lib/devices/Emulator.js' {
  declare module.exports: $Exports<'detox/lib/devices/Emulator'>;
}
declare module 'detox/lib/devices/Fbsimctl.js' {
  declare module.exports: $Exports<'detox/lib/devices/Fbsimctl'>;
}
declare module 'detox/lib/devices/Fbsimctl.test.js' {
  declare module.exports: $Exports<'detox/lib/devices/Fbsimctl.test'>;
}
declare module 'detox/lib/devices/IosNoneDevice.js' {
  declare module.exports: $Exports<'detox/lib/devices/IosNoneDevice'>;
}
declare module 'detox/lib/devices/Simulator.js' {
  declare module.exports: $Exports<'detox/lib/devices/Simulator'>;
}
declare module 'detox/lib/devices/Simulator.test.js' {
  declare module.exports: $Exports<'detox/lib/devices/Simulator.test'>;
}
declare module 'detox/lib/errors/CustomError.js' {
  declare module.exports: $Exports<'detox/lib/errors/CustomError'>;
}
declare module 'detox/lib/errors/CustomError.test.js' {
  declare module.exports: $Exports<'detox/lib/errors/CustomError.test'>;
}
declare module 'detox/lib/index.js' {
  declare module.exports: $Exports<'detox/lib/index'>;
}
declare module 'detox/lib/index.test.js' {
  declare module.exports: $Exports<'detox/lib/index.test'>;
}
declare module 'detox/lib/invoke.js' {
  declare module.exports: $Exports<'detox/lib/invoke'>;
}
declare module 'detox/lib/invoke.test.js' {
  declare module.exports: $Exports<'detox/lib/invoke.test'>;
}
declare module 'detox/lib/invoke/EarlGrey.js' {
  declare module.exports: $Exports<'detox/lib/invoke/EarlGrey'>;
}
declare module 'detox/lib/invoke/Invoke.js' {
  declare module.exports: $Exports<'detox/lib/invoke/Invoke'>;
}
declare module 'detox/lib/ios/expect.js' {
  declare module.exports: $Exports<'detox/lib/ios/expect'>;
}
declare module 'detox/lib/ios/expect.test.js' {
  declare module.exports: $Exports<'detox/lib/ios/expect.test'>;
}
declare module 'detox/lib/ios/matchers.js' {
  declare module.exports: $Exports<'detox/lib/ios/matchers'>;
}
declare module 'detox/lib/utils/argparse.js' {
  declare module.exports: $Exports<'detox/lib/utils/argparse'>;
}
declare module 'detox/lib/utils/argparse.test.js' {
  declare module.exports: $Exports<'detox/lib/utils/argparse.test'>;
}
declare module 'detox/lib/utils/exec.js' {
  declare module.exports: $Exports<'detox/lib/utils/exec'>;
}
declare module 'detox/lib/utils/exec.test.js' {
  declare module.exports: $Exports<'detox/lib/utils/exec.test'>;
}
declare module 'detox/lib/utils/retry.js' {
  declare module.exports: $Exports<'detox/lib/utils/retry'>;
}
declare module 'detox/lib/utils/retry.test.js' {
  declare module.exports: $Exports<'detox/lib/utils/retry.test'>;
}
declare module 'detox/lib/utils/uuid.js' {
  declare module.exports: $Exports<'detox/lib/utils/uuid'>;
}
declare module 'detox/local-cli/detox-build.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-build'>;
}
declare module 'detox/local-cli/detox-init.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-init'>;
}
declare module 'detox/local-cli/detox-run-server.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-run-server'>;
}
declare module 'detox/local-cli/detox-test.js' {
  declare module.exports: $Exports<'detox/local-cli/detox-test'>;
}
declare module 'detox/local-cli/detox.js' {
  declare module.exports: $Exports<'detox/local-cli/detox'>;
}
declare module 'detox/local-cli/templates/mocha.js' {
  declare module.exports: $Exports<'detox/local-cli/templates/mocha'>;
}
declare module 'detox/scripts/clean-build.js' {
  declare module.exports: $Exports<'detox/scripts/clean-build'>;
}
declare module 'detox/src/client/actions/actions.js' {
  declare module.exports: $Exports<'detox/src/client/actions/actions'>;
}
declare module 'detox/src/client/AsyncWebSocket.js' {
  declare module.exports: $Exports<'detox/src/client/AsyncWebSocket'>;
}
declare module 'detox/src/client/Client.js' {
  declare module.exports: $Exports<'detox/src/client/Client'>;
}
declare module 'detox/src/configuration.js' {
  declare module.exports: $Exports<'detox/src/configuration'>;
}
declare module 'detox/src/configurations.mock.js' {
  declare module.exports: $Exports<'detox/src/configurations.mock'>;
}
declare module 'detox/src/Detox.js' {
  declare module.exports: $Exports<'detox/src/Detox'>;
}
declare module 'detox/src/devices/Device.js' {
  declare module.exports: $Exports<'detox/src/devices/Device'>;
}
declare module 'detox/src/devices/Emulator.js' {
  declare module.exports: $Exports<'detox/src/devices/Emulator'>;
}
declare module 'detox/src/devices/Fbsimctl.js' {
  declare module.exports: $Exports<'detox/src/devices/Fbsimctl'>;
}
declare module 'detox/src/devices/IosNoneDevice.js' {
  declare module.exports: $Exports<'detox/src/devices/IosNoneDevice'>;
}
declare module 'detox/src/devices/Simulator.js' {
  declare module.exports: $Exports<'detox/src/devices/Simulator'>;
}
declare module 'detox/src/errors/CustomError.js' {
  declare module.exports: $Exports<'detox/src/errors/CustomError'>;
}
declare module 'detox/src/index.js' {
  declare module.exports: $Exports<'detox/src/index'>;
}
declare module 'detox/src/invoke.js' {
  declare module.exports: $Exports<'detox/src/invoke'>;
}
declare module 'detox/src/invoke/EarlGrey.js' {
  declare module.exports: $Exports<'detox/src/invoke/EarlGrey'>;
}
declare module 'detox/src/invoke/Invoke.js' {
  declare module.exports: $Exports<'detox/src/invoke/Invoke'>;
}
declare module 'detox/src/ios/expect.js' {
  declare module.exports: $Exports<'detox/src/ios/expect'>;
}
declare module 'detox/src/ios/matchers.js' {
  declare module.exports: $Exports<'detox/src/ios/matchers'>;
}
declare module 'detox/src/utils/argparse.js' {
  declare module.exports: $Exports<'detox/src/utils/argparse'>;
}
declare module 'detox/src/utils/exec.js' {
  declare module.exports: $Exports<'detox/src/utils/exec'>;
}
declare module 'detox/src/utils/retry.js' {
  declare module.exports: $Exports<'detox/src/utils/retry'>;
}
declare module 'detox/src/utils/uuid.js' {
  declare module.exports: $Exports<'detox/src/utils/uuid'>;
}
declare module 'detox/wallaby.js' {
  declare module.exports: $Exports<'detox/wallaby'>;
}
