// flow-typed signature: 20a891674bc73c2a12a52fcf9eee0f43
// flow-typed version: <<STUB>>/react-native-camera-kit_v^5.2.13/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-camera-kit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-camera-kit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-camera-kit/src/CameraKitCamera.android' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraKitCamera.ios' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraKitGallery.android' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraKitGallery.ios' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraKitGalleryView.android' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraKitGalleryView.ios' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreen.android' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreen.ios' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreenBase' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreenStyleObject.android' {
  declare module.exports: any;
}

declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreenStyleObject.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-camera-kit/index' {
  declare module.exports: $Exports<'react-native-camera-kit'>;
}
declare module 'react-native-camera-kit/index.js' {
  declare module.exports: $Exports<'react-native-camera-kit'>;
}
declare module 'react-native-camera-kit/src/CameraKitCamera.android.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraKitCamera.android'>;
}
declare module 'react-native-camera-kit/src/CameraKitCamera.ios.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraKitCamera.ios'>;
}
declare module 'react-native-camera-kit/src/CameraKitGallery.android.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraKitGallery.android'>;
}
declare module 'react-native-camera-kit/src/CameraKitGallery.ios.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraKitGallery.ios'>;
}
declare module 'react-native-camera-kit/src/CameraKitGalleryView.android.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraKitGalleryView.android'>;
}
declare module 'react-native-camera-kit/src/CameraKitGalleryView.ios.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraKitGalleryView.ios'>;
}
declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreen.android.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreen.android'>;
}
declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreen.ios.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreen.ios'>;
}
declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreenBase.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreenBase'>;
}
declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreenStyleObject.android.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreenStyleObject.android'>;
}
declare module 'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreenStyleObject.ios.js' {
  declare module.exports: $Exports<'react-native-camera-kit/src/CameraScreen/CameraKitCameraScreenStyleObject.ios'>;
}
